import Foundation
import XCTest
@testable import PhrenKit

/// `PendingOpsQueue.load` and `LocalStore.init` both swallow decode failures
/// and fall back to empty — a queue that fails to decode takes every unpushed
/// user mutation with it, silently, on upgrade. These tests are the tripwire:
/// they must keep passing unchanged as the sync layer evolves.
///
/// `pending-ops-legacy.json` was generated by the shipping build's own encoder,
/// not written by hand, so it reflects the real on-disk shape — including that
/// nil associated values are omitted rather than encoded as null.
final class PersistenceMigrationTests: XCTestCase {

    func testLegacyPendingOpsJSONDecodesEveryCase() throws {
        let data = try Data(contentsOf: try Fixtures.url("pending-ops-legacy.json"))
        let queue = try JSONDecoder().decode(PendingOpsQueue.self, from: data)

        XCTAssertEqual(queue.pending.count, 14, "an op was silently dropped on decode")
        XCTAssertEqual(queue.failed.count, 1)

        // Every PendingOp case must survive the round trip. Compare on the case
        // itself, not just the count, so a renamed case fails loudly here rather
        // than discarding a user's queued work in the field.
        let decoded = queue.pending.map(\.op)
        XCTAssertEqual(decoded[0], .addFinding(project: "myproj", text: "Legacy queued finding", type: "pattern"))
        XCTAssertEqual(decoded[1], .editFinding(project: "myproj", match: "6957f9f8", newText: "Legacy edit"))
        XCTAssertEqual(decoded[2], .removeFinding(project: "myproj", match: "38209d83"))
        XCTAssertEqual(decoded[3], .approveQueue(project: "myproj", line: "- [2026-07-26] Legacy queue line"))
        XCTAssertEqual(decoded[4], .rejectQueue(project: "myproj", line: "- [2026-07-26] Legacy queue line"))
        XCTAssertEqual(decoded[5], .editQueue(project: "myproj", line: "- [2026-07-26] Legacy queue line",
                                              newText: "Legacy queue edit"))
        XCTAssertEqual(decoded[6], .addNote(project: "myproj", date: "2026-07-25", time: "09:15:00",
                                            text: "Legacy note"))
        XCTAssertEqual(decoded[7], .editNote(project: "myproj", date: "2026-07-25", stableId: "5588c05d",
                                             text: "Legacy note edit"))
        XCTAssertEqual(decoded[8], .removeNote(project: "myproj", date: "2026-07-25", stableId: "5588c05d"))
        XCTAssertEqual(decoded[9], .promoteNote(project: "myproj", date: "2026-07-25", stableId: "5588c05d",
                                                findingType: "pitfall"))
        XCTAssertEqual(decoded[10], .addTask(project: "myproj", text: "Legacy task"))
        XCTAssertEqual(decoded[11], .completeTask(project: "myproj", match: "013d708f"))
        XCTAssertEqual(decoded[12], .removeTask(project: "myproj", match: "aa853063"))
        XCTAssertEqual(decoded[13], .updateTask(project: "myproj", match: "013d708f", text: "Legacy task update",
                                                priority: "high", section: "active"))

        // Retry bookkeeping and parked-op diagnostics survive too.
        XCTAssertEqual(queue.pending[1].attempts, 1)
        XCTAssertNotNil(queue.pending[1].lastError)
        XCTAssertEqual(queue.failed[0].attempts, 3)
        XCTAssertEqual(queue.failed[0].op, .addFinding(project: "myproj", text: "Legacy parked finding", type: nil))
    }

    /// `load` must never turn a decodable queue into an empty one — the failure
    /// mode that loses work is silent, so assert through the real entry point.
    func testLoadPreservesQueueThroughRealEntryPoint() throws {
        let dir = FileManager.default.temporaryDirectory
            .appendingPathComponent("phren-queue-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: dir) }

        let url = dir.appendingPathComponent("pending-ops.json")
        try Data(contentsOf: try Fixtures.url("pending-ops-legacy.json")).write(to: url)

        let loaded = PendingOpsQueue.load(from: url)
        XCTAssertEqual(loaded.pending.count, 14)
        XCTAssertEqual(loaded.failed.count, 1)
    }

    /// Blob shas are what make incremental pulls and optimistic-concurrency
    /// writes work; a silent manifest reset forces a full re-download and can
    /// strand locally-applied edits.
    func testManifestSurvivesReopen() async throws {
        let dir = FileManager.default.temporaryDirectory
            .appendingPathComponent("phren-manifest-\(UUID().uuidString)")
        defer { try? FileManager.default.removeItem(at: dir) }

        let store = try LocalStore(rootDirectory: dir, owner: "o", repo: "r", branch: "main")
        try await store.write("myproj/FINDINGS.md", content: "# myproj Findings\n", blobSha: "sha-abc")
        try await store.updateManifest { $0.headSha = "head-7" }

        let reopened = try LocalStore(rootDirectory: dir, owner: "o", repo: "r", branch: "main")
        let manifest = await reopened.currentManifest
        XCTAssertEqual(manifest.headSha, "head-7")
        XCTAssertEqual(manifest.blobShas["myproj/FINDINGS.md"], "sha-abc")
        let sha = await reopened.blobSha(for: "myproj/FINDINGS.md")
        XCTAssertEqual(sha, "sha-abc")
    }
}
