import Foundation
import PhrenKit

/// Offline demo mode: seeds two local stores with markdown fixtures so the whole
/// app — projects, findings, tasks, review queue, search, multi-store badges,
/// read-only handling — can be explored without GitHub auth.
///
/// Nothing here touches the network. The seeded files are written through the
/// real `LocalStore`, so `snapshot()` runs the same parsers the live app uses.
///
/// Remove this file (and the "Explore the demo" button in `WelcomeView`) to drop
/// demo mode entirely.
enum DemoMode {

    /// A demo store: a descriptor plus the markdown files to seed it with.
    struct Seed {
        let descriptor: StoreDescriptor
        /// Repo-relative path → file contents.
        let files: [String: String]
    }

    static var seeds: [Seed] {
        [personalSeed, teamSeed]
    }

    // MARK: - Personal store (writable)

    private static var personalSeed: Seed {
        Seed(
            descriptor: StoreDescriptor(owner: "alaarab", name: "my-phren",
                                        branch: "main", canPush: true),
            files: [
                "m4l-builder/FINDINGS.md": """
                # Findings

                - [pitfall] `svf~` and `hip~` produce NO audio in Ableton Live 12. An `svf~` in a series signal path silently kills the chain — use `biquad~` with computed coefficients instead. <!-- fid:a1b2c3d4 -->
                - [pattern] gen~ cores export cleanly to RNBO; vanilla MSP with `tapin~`/`tapout~` also ports. `pfft~` is the one hard blocker — it has no RNBO equivalent. <!-- fid:b2c3d4e5 -->
                - [decision] Device UI is dark-only. The `live.colors` theme bus reads Ableton's theme at runtime rather than hardcoding swatches. <!-- fid:c3d4e5f6 -->
                - [pitfall] A `loadbang → message 1 → live.text` default is stomped by the live.* value-restore that runs AFTER loadbang on device load, leaving the toggle OFF. Make it a real parameter instead. <!-- fid:d4e5f607 -->

                """,

                "m4l-builder/tasks.md": """
                # Tasks

                ## Active

                - [ ] Port Pressure + Heat gen~ cores to RNBO and verify offline render [high] <!-- bid:11aa22bb -->
                - [ ] Para EQ pass 2 — merge band column into a single bottom row <!-- bid:22bb33cc -->

                ## Queue

                - [ ] Multiband correlation strip (differentiator vs stock meters) <!-- bid:33cc44dd -->
                - [ ] Investigate `pfft~` replacement in gen~ for Linear Phase EQ <!-- bid:44dd55ee -->
                - [ ] Sample-pack QC gate: automated loudness + phase checks <!-- bid:55ee66ff -->

                ## Done

                - [x] Ceiling limiter — dither stage shipped <!-- bid:66ff7700 -->
                - [x] Echotide tempo sync via plugsync~ <!-- bid:77008811 -->

                """,

                "m4l-builder/review.md": """
                # Review Queue

                - [ ] [pattern] Knob drag should support shift for fine-tune and cmd for axis-lock <!-- rid:aa11bb22 -->
                - [ ] [pitfall] `ondragend` does not exist in jsui — detect release via `button === 0` inside ondrag <!-- rid:bb22cc33 -->

                """,

                "m4l-builder/notes/2026-07-25.md": """
                # 2026-07-25

                ## 14:22:10

                Spectrum analyzer K-weighting matches the reference curve within 0.3 dB across the band.

                ## 16:48:03

                Gordita clip stage sounds better with the tanh~ ahead of the overdrive~, not after.

                """,

                "phren/FINDINGS.md": """
                # Findings

                - [architecture] The iOS app is serverless — a phren store is a git repo of markdown and git is the sync layer, so the app talks straight to the GitHub REST API. No backend. <!-- fid:e5f60718 -->
                - [decision] Markdown parsers in PhrenKit are line-by-line transcriptions of the CLI's TypeScript. Fixtures are generated by the real CLI, never hand-written, and tests assert byte-identical output. <!-- fid:f6071829 -->
                - [pattern] Reads use `If-None-Match` ETags so 304s don't count against the GitHub rate limit. Live mode polls every ~7s while foregrounded. <!-- fid:0718293a -->

                """,

                "phren/tasks.md": """
                # Tasks

                ## Active

                - [ ] Register the GitHub OAuth App and replace the placeholder client ID [high] <!-- bid:8811992a -->

                ## Queue

                - [ ] Journal-based writes for team stores <!-- bid:992aaa3b -->
                - [ ] 3D graph tab (parity with the web UI) <!-- bid:aa3bbb4c -->

                ## Done

                - [x] Multi-store support with per-store badges <!-- bid:bb4ccc5d -->

                """,

                "phren/summary.md": """
                Open-source knowledge layer for AI agents. Published as `@phren/cli` on npm.
                """,

                "alphalens/FINDINGS.md": """
                # Findings

                - [pitfall] `vite build` needs `NODE_OPTIONS=--max-old-space-size=1280` on the 1 GB Linode or V8 OOMs mid-build. <!-- fid:293a4b5c -->
                - [decision] Bot and website share one SQLite file; WAL mode handles the concurrency. Schema lives in `packages/schema/src/ddl.ts`. <!-- fid:3a4b5c6d -->

                """,

                "alphalens/tasks.md": """
                # Tasks

                ## Active

                - [ ] Trench mode tab in the mobile app <!-- bid:cc5ddd6e -->

                ## Queue

                - [ ] Jupiter swap terminal (no DEX frontend fees) <!-- bid:dd6eee7f -->

                """,
            ]
        )
    }

    // MARK: - Team store (read-only — exercises the canPush: false path)

    private static var teamSeed: Seed {
        Seed(
            descriptor: StoreDescriptor(owner: "acme-eng", name: "team-phren",
                                        branch: "main", canPush: false),
            files: [
                "intrapath/FINDINGS.md": """
                # Findings

                - [architecture] Every scoped table has `ENABLE`/`FORCE ROW LEVEL SECURITY` with a `tenant_id` default from `current_setting('app.tenant_id')`. `withTenant(id, fn)` opens a tx and sets the config. <!-- fid:4b5c6d7e -->
                - [pitfall] The pre-push hook runs the full suite — typecheck, lint, size, raw-drizzle and route-scope checks, plus 1158 vitest cases. Budget ~2 minutes for any push. <!-- fid:5c6d7e8f -->
                - [decision] Verification gate is flagged off in production because outbound email isn't wired yet. <!-- fid:6d7e8f90 -->

                """,

                "intrapath/tasks.md": """
                # Tasks

                ## Active

                - [ ] Wire outbound email so the verification gate can be enabled [high] <!-- bid:ee7fff80 -->

                ## Queue

                - [ ] Per-tenant email log with send/skip/fail status <!-- bid:ff800091 -->
                - [ ] Notification templates keyed by entity.action <!-- bid:001191a2 -->

                """,

                "intrapath/review.md": """
                # Review Queue

                - [ ] [tradeoff] Admin index pages are generated by a config-driven factory — less flexible per-resource, far less duplication <!-- rid:cc33dd44 -->

                """,

                "atlas/FINDINGS.md": """
                # Findings

                - [pattern] Atlas is signup-based multi-tenant with no seed admin; org creation is capped per account via `ATLAS_MAX_ORGS_PER_USER`. <!-- fid:1191a2b3 -->

                """,

                "atlas/tasks.md": """
                # Tasks

                ## Queue

                - [ ] Renew the wildcard TLS cert before it expires (manual DNS-01) <!-- bid:1191a2b3 -->

                """,
            ]
        )
    }

    /// Where demo stores live — separate from real store directories so demo
    /// mode can never collide with or clobber a signed-in user's cache.
    static func directory(for descriptor: StoreDescriptor) -> URL {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first
            ?? FileManager.default.temporaryDirectory
        return base.appendingPathComponent("PhrenDemo/\(descriptor.owner)__\(descriptor.name)",
                                           isDirectory: true)
    }
}
